server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848         #Nacos\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  # ==========applicationName + druid-mysql8 driver===================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 961718787
# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.cloud.entities
  configuration:
    map-underscore-to-camel-case: true



# ========================seata===================
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server
  tx-service-group: default_tx_group # \u4E8B\u52A1\u7EC4\uFF0C\u7531\u5B83\u83B7\u5F97TC\u670D\u52A1\u7684\u96C6\u7FA4\u540D\u79F0
  service:
    vgroup-mapping:
      default_tx_group: default # \u4E8B\u52A1\u7EC4\u4E0ETC\u670D\u52A1\u96C6\u7FA4\u7684\u6620\u5C04\u5173\u7CFB
  data-source-proxy-mode: AT

logging:
  level:
    io:
      seata: info